---
- name: Obtener datos del segundo tenista desde la API
  uri:
    url: "https://randomuser.me/api/?results=1&noinfo"
    method: GET
    return_content: yes
    body_format: json
    status_code: 200
    timeout: 30
  register: random_user
  retries: 3
  delay: 5
  until: random_user.status == 200

- name: Extraer y formatear datos del API
  set_fact:
    api_first_name: "{{ random_user.json.results[0].name.first | capitalize }}"
    api_last_name: "{{ random_user.json.results[0].name.last | capitalize }}"
    api_city: "{{ random_user.json.results[0].location.city | capitalize }}"
    api_id: "{{ random_user.json.results[0].login.uuid }}"

- name: Crear archivo con información del partido
  copy:
    content: |
      ** INFORMACION DEL PARTIDO UNIR **
      
      First Name: {{ first_name }}.
      Last Name: {{ last_name }}.
      City: {{ city }}.
      id: {{ id }}.
      
      First Name: {{ api_first_name }}.
      Last Name: {{ api_last_name }}.
      City: {{ api_city }}.
      id: {{ api_id }}.
      
      Fecha: {{ ansible_date_time.iso8601 }}.
    dest: "{{ output_dir }}/partido.txt"
    mode: 0644